title: "Bloody CMS"
header: "header.png"

home:
  enabled: true
  in_nav: true
  title: "home"

blog:
  enabled: true         #toggles wether this feature is enabled
  in_nav: true          #toggles wether this feature is shown in the sidebar
  title: "news"         #the title for the sidebar
  path: "news"          #the path used in the url (e.g. http://example.com/your_path/post_name)

pages:
  enabled: true         #toggles wether this feature is enabled
  in_nav: true          #toggles wether this feature is shown in the sidebar
