title: "Bloody CMS"
header: "header.png"

sidebar:
  blocks:
    eventbrite: '<div style="width:195px; text-align:center;" ><iframe  src="http://www.eventbrite.com/countdown-widget?eid=1920013813" frameborder="0" height="271" width="195" marginheight="0" marginwidth="0" scrolling="no" allowtransparency="true"></iframe>'
      
home:
  enabled: true         # wether to show the sidebar home module
  in_nav: true          # wether to actually show it in the sidebar
  sidebar_title: "home" # the title for in the sidebar

blog:
  enabled: true         #toggles wether this feature is enabled
  in_nav: true          #toggles wether this feature is shown in the sidebar
  title: "News"         #the title for this section
  sidebar_title: "news" #the title for the sidebar
  path: "news"          #the path used in the url (e.g. http://example.com/your_path/post_name)
  show_recent: 2        #wether or not to show the recent blogs entries on the frontpage
  
pages:
  enabled: true         #toggles wether this feature is enabled
  in_nav: true          #toggles wether this feature is shown in the sidebar
  root_page: "home"    #the root page to show instead of the blog
  
twitter:
  consumer_key: 'oTtUoZEdLvrYV0s5xs6Pw'
  consumer_secret: 'CE8TvlUxEdMqGq0MS3QYYEpoeR9YO4hgx1TIZR5KwU'